// this code is generated by chatgpt

import React from "react";
import styled, { keyframes } from "styled-components";

// Define the shimmer animation
const shimmer = keyframes`
  0% {
    background-position: -200px 0;
  }
  100% {
    background-position: 200px 0;
  }
`;

// Skeleton container
const SkeletonContainer = styled.div`
  display: flex;
  flex-direction: column;
  gap: 16px;
`;

// Skeleton for heading
const SkeletonHeading = styled.div`
  width: 60%;
  height: 32px;
  background: #e0e0e0;
  background: linear-gradient(90deg, #e0e0e0 25%, #f5f5f5 50%, #e0e0e0 75%);
  background-size: 200% 100%;
  animation: ${shimmer} 1.5s infinite linear;
  border-radius: 4px;
  margin: 32px 0 8px 0;
`;

// Skeleton for list items
const SkeletonListItem = styled.div`
  width: 100%;
  height: 16px;
  background: #e0e0e0;
  background: linear-gradient(90deg, #e0e0e0 25%, #f5f5f5 50%, #e0e0e0 75%);
  background-size: 200% 100%;
  animation: ${shimmer} 1.5s infinite linear;
  border-radius: 4px;
`;

const SkeletonList = styled.div`
  display: flex;
  flex-direction: column;
  gap: 8px;
`;

// React Component
const LoadingSkeleton = () => {
  return (
    <SkeletonContainer>
      <SkeletonHeading />
      <SkeletonList>
        <SkeletonListItem />
        <SkeletonListItem />
        <SkeletonListItem />
        {/* Add more items as needed */}
      </SkeletonList>
      <SkeletonHeading />
      <SkeletonList>
        <SkeletonListItem />
        <SkeletonListItem />
        <SkeletonListItem />
        {/* Add more items as needed */}
      </SkeletonList>
    </SkeletonContainer>
  );
};

export default LoadingSkeleton;
