function Spacetech() {
    return (
      <main style={{ minHeight: "calc(100vh - 150px)" }}>
        <h1>SpaceTech</h1>
        <h3> Lorem ipsum dolor sit amet </h3>
        <p> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Rhoncus dolor purus non enim praesent elementum facilisis leo vel. Aliquam ut porttitor leo a diam sollicitudin. Ullamcorper eget nulla facilisi etiam dignissim diam. Amet est placerat in egestas erat. Aliquam etiam erat velit scelerisque in dictum non consectetur. At tempor commodo ullamcorper a lacus vestibulum sed. Fermentum posuere urna nec tincidunt praesent semper feugiat nibh. Quam pellentesque nec nam aliquam sem et tortor. Erat nam at lectus urna duis convallis convallis. Eget mi proin sed libero.

Laoreet suspendisse interdum consectetur libero id faucibus. Volutpat commodo sed egestas egestas. Duis ut diam quam nulla porttitor massa id neque aliquam. Blandit massa enim nec dui nunc mattis enim. Habitant morbi tristique senectus et. Eleifend mi in nulla posuere sollicitudin. Nibh mauris cursus mattis molestie a iaculis at. At erat pellentesque adipiscing commodo elit at imperdiet. Ligula ullamcorper malesuada proin libero nunc. Nunc sed id semper risus in. Morbi tincidunt augue interdum velit euismod in pellentesque massa placerat. Curabitur gravida arcu ac tortor dignissim convallis aenean. Vitae nunc sed velit dignissim sodales ut. Sagittis orci a scelerisque purus semper eget duis at tellus. Penatibus et magnis dis parturient montes nascetur ridiculus mus mauris. Ullamcorper velit sed ullamcorper morbi tincidunt ornare massa eget. At urna condimentum mattis pellentesque id nibh.

Leo integer malesuada nunc vel risus commodo viverra maecenas. Quis eleifend quam adipiscing vitae proin sagittis. Elit duis tristique sollicitudin nibh sit amet commodo nulla facilisi. Iaculis nunc sed augue lacus. Eu feugiat pretium nibh ipsum consequat nisl vel pretium. Malesuada pellentesque elit eget gravida cum sociis natoque penatibus et. Malesuada fames ac turpis egestas maecenas pharetra convallis posuere. Volutpat lacus laoreet non curabitur. Amet aliquam id diam maecenas ultricies. Consequat ac felis donec et. Elit scelerisque mauris pellentesque pulvinar pellentesque habitant morbi. Lectus urna duis convallis convallis tellus id interdum velit laoreet. Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Viverra suspendisse potenti nullam ac. Fringilla est ullamcorper eget nulla facilisi etiam dignissim. Non nisi est sit amet facilisis magna etiam tempor. Amet mattis vulputate enim nulla aliquet porttitor. Nunc eget lorem dolor sed viverra. Dui id ornare arcu odio. Interdum velit laoreet id donec ultrices tincidunt arcu non.

Luctus accumsan tortor posuere ac ut. Tellus rutrum tellus pellentesque eu tincidunt tortor aliquam. Eget sit amet tellus cras adipiscing enim. Proin fermentum leo vel orci porta non pulvinar neque. Quam elementum pulvinar etiam non quam lacus suspendisse faucibus. Vulputate sapien nec sagittis aliquam malesuada bibendum arcu vitae. Sapien faucibus et molestie ac feugiat sed lectus vestibulum mattis. Lorem dolor sed viverra ipsum. Nec dui nunc mattis enim ut tellus elementum sagittis vitae. Pellentesque habitant morbi tristique senectus et netus. Magna ac placerat vestibulum lectus mauris. Vel facilisis volutpat est velit egestas. Quisque id diam vel quam elementum pulvinar etiam non quam. Integer malesuada nunc vel risus commodo. Metus dictum at tempor commodo ullamcorper. Eget sit amet tellus cras adipiscing enim eu turpis. At consectetur lorem donec massa sapien faucibus et. Proin fermentum leo vel orci. Eget mauris pharetra et ultrices. </p>
      </main>
    );
  }
  
  export default Spacetech;
  