name: Check Build and Export
on:
  pull_request:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false

      - name: Install and Build
        uses: actions/setup-node@v1
        with:
          node-version: 17
      - run: npm install
      - run: npm run build # runs `next build`
      - run: npm run export # runs `next export`
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
