name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
          
      - name: Add .env variables
        env:
          NEXT_PUBLIC_AIRTABLE_API_KEY: ${{ secrets.NEXT_PUBLIC_AIRTABLE_API_KEY }}
          NEXT_PUBLIC_AIRTABLE_BASE_ID: ${{ secrets.NEXT_PUBLIC_AIRTABLE_BASE_ID }}
        run:
          echo NEXT_PUBLIC_AIRTABLE_API_KEY=$NEXT_PUBLIC_AIRTABLE_API_KEY >> .env
          echo NEXT_PUBLIC_AIRTABLE_BASE_ID=$NEXT_PUBLIC_AIRTABLE_BASE_ID >> .env

      - name: Install and Build
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - run: npm run build # runs `next build`
      - run: npm run export # runs `next export`
        env:
          CI: true
          DEPLOY_TARGET: gh-pages
      - run: touch out/.nojekyll

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: out # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
